languageCode = "en-us"
title = "jdb's technical notes"
theme = "hugo-dusk"
baseURL = "https://boydj.github.io/blog/"
canonifyURLS = true

[author]
  name = "Josh Boyd"

[params]
  github = "boydj"
  twitter = "joshboyd"
  linkedin = "joshuaboyd"
  theme_colors = "default-dark"
  utterancesRepo = "boydj/blog"
  utterancesTheme = "github-dark"
  utterancesIssueTerm="pathname"
